In [2]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)#Devuelve una tupla con las dimensiones del array.
print(array.size)#Devuelve el número total de elementos en el array.
print(array.ndim)#Devuelve el número de dimensiones del array.

(2, 3)
6
2


In [3]:
array_reshape = array.reshape((3, 2))#Cambia la forma del array sin cambiar sus datos.
print(array_reshape)
array_flatten = array.flatten()#Convierte un array multidimensional en un array unidimensional.
print(array_flatten)


[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [2]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array[1, 2])  # Elemento en la fila 1, columna 2
print(array[0:2, 1:3])  # Subarray desde fila 0 a 1 y columna 1 a 2
#array[fila_inicio:fila_final, columna_inicio:columna_final]



6
[[2 3]
 [5 6]]


In [6]:
array = np.array([1, 2, 3, 4, 5])
print(np.sum(array))  # Suma de todos los elementos
print(np.prod(array))  # Producto de todos los elementos
print(np.mean(array))  # Media (promedio)
print(np.median(array))  # Mediana
print(np.std(array))  # Desviación estándar
print(np.var(array))  # Varianza
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
columna_2 = array[:, 1]  # Selecciona la segunda columna
print(np.sum(columna_2))  # Suma los valores de la segunda columna

15
120
3.0
3.0
1.4142135623730951
2.0
15


In [12]:
x= np.array([
    [[0,1],
    [2,3]],

    [[4,5],
    [6,7]]
])
result_a0= np.sum(x,axis=0)##elementos de la misma posicion pero diferente arrays ej: [0+4 1+5][2+6 3+7]
result_a1= np.sum(x,axis=1)##diferentes filas en cada array ej: [0+2 1+3][4+6 5+7]
result_a2= np.sum(x,axis=2)##diferentes columnas en cada array ej: [0+1 2+3][4+5 6+7]
print(f"{result_a0} \n {result_a1} \n {result_a2}")

[[ 4  6]
 [ 8 10]] 
 [[ 2  4]
 [10 12]] 
 [[ 1  5]
 [ 9 13]]
